services:
  # Backend Web Service
  - type: web
    name: freshmarket-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5001
      - key: ALLOWED_ORIGIN
        value: https://freshmarket-frontend.onrender.com
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false

  # Frontend Web Service
  - type: web
    name: freshmarket-frontend
    plan: free
    env: node
    rootDir: frontend
    buildCommand: npm install --include=dev && NODE_OPTIONS=--max_old_space_size=400 npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: freshmarket-backend
          envVarKey: RENDER_EXTERNAL_URL
